# 1. Import NUMPY as np

In [1]:
import numpy as np

# 2.Create a null vector of size 10

In [64]:
a=np.zeros(10,dtype=int)
print(a)

[0 0 0 0 0 0 0 0 0 0]


# 3.Create a null vector of size 10 but the fifth value which is 1

In [65]:
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


# 4.Create a vector with values ranging from 10 to 49

In [13]:
b=np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 5.Reverse a vector (the first element becomes last)

In [16]:
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

# 6.Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
matrix=np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 7.Find indices of non­zero elements from [1,2,0,0,4,0]

In [23]:
ele=[1,2,0,0,4,0]
print(ele)

[1, 2, 0, 0, 4, 0]


In [24]:
np.nonzero(ele)

(array([0, 1, 4], dtype=int64),)

# 8.Create a 3x3x3 array with random values

In [158]:
Matrix=np.random.randint(10,size=(3,3))
print(Matrix)

[[5 6 3]
 [6 0 3]
 [7 3 7]]


# 9.Create a random vector of size 30 and find the mean value

In [159]:
vector= np.random.randint(50,size=30)
print(vector)


[ 7 32 22 44 47 43 36 32 25 47 20 17 21 32 26 21 42 38  0 39 30 27 35 13
 28 16 39 24 31 18]


In [160]:
np.mean(vector)

28.4

# 10.Create a 2d array with 1 on the border and 0 inside

In [53]:
array1=[1,1,1,1,0,1,1,1,1]
print(array1)

[1, 1, 1, 1, 0, 1, 1, 1, 1]


In [58]:
np.reshape(array1,(3,3))

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

# 11.Create an 8x8 matrix and fill it with a checkerboard pattern

In [69]:
c=np.zeros((8,8),dtype=int)
print(c)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [97]:
c[1::2,::2]=0
print(c)

[[0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]]


# 12.What is the major difference between sets, lists, tuples and dictionaries?

## Sets: They are declared in flower braces{ }. They are unordered and unindexed.
             

In [100]:
#eg for sets
set_1={"Dhana","Sree","S"}
print(set_1)
#can Add new elements and can do other funcyions like removing,updating,pop etc.
set_1.add("Greycampus")
print(set_1)

{'Dhana', 'Sree', 'S'}
{'Greycampus', 'Dhana', 'Sree', 'S'}


## Lists: They are declared using square braces[ ].They can contain duplicate values. They are mutable i.e; the values can be changed

In [108]:
#eg for lists
list_1=["hi","this","is","dhana","hi"]
print(list_1)
#removing a value in list
list_1.remove("hi")
print(list_1)
#appending means adding a new value to the list
list_1.append("sree")
print(list_1)

['hi', 'this', 'is', 'dhana', 'hi']
['this', 'is', 'dhana', 'hi']
['this', 'is', 'dhana', 'hi', 'sree']


## Tuples: They are defined using round  braces( ).They are immutable i.e: the values cannot be changed.

In [111]:
#eg for tuples
tuple_1=(1,23,5,67,2)
print(tuple_1)
#cannot be changed
tuple_1.remove(1)

(1, 23, 5, 67, 2)


AttributeError: 'tuple' object has no attribute 'remove'

## Dictionaries: They are defined using the flower braces { }. They contain a key paired with its values.They are unordered and do not allow duplicate values.

In [142]:
#eg for dictionaries
dict_1={"key1":"hello","key2":"Everyone","key3":"bye"}
print(dict_1)
#adding a key and value
dict_1["key4"]="greycampus"
print(dict_1)
#deleting a key and value
del dict_1["key3"]
print(dict_1)
#to change a key value we overwrite it
dict_1["key4"]="sup?"
print(dict_1)

{'key1': 'hello', 'key2': 'Everyone', 'key3': 'bye'}
{'key1': 'hello', 'key2': 'Everyone', 'key3': 'bye', 'key4': 'greycampus'}
{'key1': 'hello', 'key2': 'Everyone', 'key4': 'greycampus'}
{'key1': 'hello', 'key2': 'Everyone', 'key4': 'sup?'}


# 13.Print first 10 natural numbers using while loop

In [127]:
a=1
while a<=10:
    print(a)
    a+=1


1
2
3
4
5
6
7
8
9
10


# 14.Print the numbers -10 to -1 using for loop.

In [139]:
start=-10
end=0
for x in range(start,end):
    print(x)


-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


# 15.Print the message “Done” after successful execution of any for a loop. 

In [141]:
a=2
if a<2:
    print("less than 2")
else:
    print("equal or greater than 2")
print("DONE")

equal or greater than 2
DONE


# 16.Create a random vector of size 10 and sort it

In [157]:
sorting=np.random.randint(10,size=10)
print("Before sort:",sorting,"\n")
sorting.sort()
print("After sort:",sorting)

Before sort: [2 9 7 8 2 1 7 4 0 5] 

After sort: [0 1 2 2 4 5 7 7 8 9]


# 17.Execute any three math functions using NumPy.

In [171]:
y=np.array([2,3,4,5])
z=np.array([3,9,1,2])
#sum of two arrays
print("Sum of two arrays:",np.add(y,z))

#square root values of array y
print("Square root of y:",np.sqrt(y))

#floor values of array z
print("Floor values of array z:",np.floor(z))

#exponential of 2 values
print("Exponential of 2 values of array y:",np.exp2(y))

#returns trignometric sine values of the array
print("Sine values of array z:",np.sin(z))

Sum of two arrays: [ 5 12  5  7]
Square root of y: [1.41421356 1.73205081 2.         2.23606798]
Floor values of array z: [3. 9. 1. 2.]
Exponential of 2 values of array y: [ 4.  8. 16. 32.]
Sine values of array z: [0.14112001 0.41211849 0.84147098 0.90929743]
